#!/bin/bash

if [ "x${UCVM_INSTALL_PATH}" != "x" ]; then
  if [ -d ${UCVM_INSTALL_PATH}/model/cvmhlabn/lib ]; then
     source ${UCVM_INSTALL_PATH}/conf/ucvm_env.sh
     ./unittest
    exit
  fi
fi

env DYLD_LIBRARY_PATH=../src ./unittest
