name: cvmhlabn-ucvm-ci

on:
  push:
    branches: [ main ]

jobs:
  cvmhlabn-build-ucvm-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/cvmhlabn/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/cvmhlabn/target" >> $GITHUB_ENV
### build ucvm(basin) first 
    - id: get-ucvm 
      uses: actions/checkout@v2
      with: 
        repository: 'SCECcode/UCVM'
        ref: basin
        path: ucvm
    - id: look-around
      run: ( echo " pwd =>"; pwd;
             echo " ls =>"; ls;
             echo " RUNNER_WORKSPACE =>"$RUNNER_WORKSPACE;
             echo " UCVM_SRC_PATH =>"$UCVM_SRC_PATH;
             echo " github.action_path =>"${{ github.action_path }};)
      shell: bash
    - id: build-ucvm
      uses: $UCVM_SRC_PATH/.github/actions/action_ucvm
      with:
        target-model: 'cvmh'
    - id: get-result
      run: echo ${{ steps.build-ucvm.outputs.build-log }}
      shell: bash
### build cvmhlabn at the ucvm's model location  
#    - name: move to the model location
#      run: (cd $UCVM_SRC_PATH/work/model)
#      shell: bash
#    - name: checkout cvmhlabn main
#      uses: actions/checkout@v2
#      with: 
#        path: $RUNNER_WORKSPACE/cvmhlabn/ucvm/work/model/cvmhlabn
#    - run: ( echo " pwd =>"; pwd;
#             echo " ls =>"; ls;
#             echo " RUNNER_WORKSPACE =>"$RUNNER_WORKSPACE;
#             echo " github.action_path =>"${{ github.action_path }};)
#      shell: bash
#    - name: build cvmhlabn with ucvm
#      run: ./.github/scripts/cvmhlabn-build-ucvm.sh 
#      shell: bash
#    - name: test cvmhlabn with ucvm
#      run: ./.github/scripts/cvmhlabn-test-ucvm.sh
#      shell: bash
