name: cvmhlabn-ucvm-ci

on:
  push:
    branches: [ main ]

jobs:
  cvmhlabn-build-ucvm-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/target" >> $GITHUB_ENV
### build ucvm(basin) first 
    - id: build-ucvm 
      uses: actions/checkout@v2
      with: 
        repository: 'SCECcode/UCVM'
        ref: basin
        path: ucvm
    - run: ( echo " pwd =>"; pwd;
             echo " ls =>"; ls;
             echo " RUNNER_WORKSPACE =>"$RUNNER_WORKSPACE;
             echo " github.action_path =>"${{ github.action_path }};)
      shell: bash
### build cvmhlabn at the ucvm's model location  
#    - name: move to the model location
#      run: (cd $UCVM_SRC_PATH/work/model)
#      shell: bash
    - name: checkout cvmhlabn main
      uses: actions/checkout@v2
      with: 
        path: main
    - run: ( echo " pwd =>"; pwd;
             echo " ls =>"; ls;
             echo " RUNNER_WORKSPACE =>"$RUNNER_WORKSPACE;
             echo " github.action_path =>"${{ github.action_path }};)
      shell: bash
#    - name: build cvmhlabn with ucvm
#      run: ./.github/scripts/cvmhlabn-build-ucvm.sh 
#      shell: bash
#    - name: test cvmhlabn with ucvm
#      run: ./.github/scripts/cvmhlabn-test-ucvm.sh
#      shell: bash
