name: cvmhlabn-ucvm-ci

on:
  push:
    branches: [ main ]

jobs:
  cvmhlabn-build-ucvm-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/cvmhlabn/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/cvmhlabn/target" >> $GITHUB_ENV
### build ucvm(basin) first 
    - id: get-ucvm 
      uses: actions/checkout@v2
      with: 
        repository: 'SCECcode/UCVM'
        ref: basin
        path: ucvm
    - id: look-around
      run: ( echo " cvmhlabn-ucvm-ci:pwd =>";pwd;
             echo " cvmhlabn-ucvm-ci:UCVM_SRC_PATH =>"$UCVM_SRC_PATH;
             echo " cvmhlabn-ucvm-ci:UCVM_INSTALL_PATH =>"$UCVM_INSTALL_PATH;
             echo " cvmhlabn-ucvm-ci:RUNNER_WORKSPACE =>"$RUNNER_WORKSPACE;
             echo " cvmhlabn-ucvm-ci:github.action_path =>"${{ github.action_path }};)
      shell: bash
    - id: build-ucvm
      uses: SCECcode/UCVM/.github/actions@v1
      with:
         initiating-repo: 'cvmhlabn'
         target-model: 'cvmhlabn'

    - id: get-result
      run: echo ${{ steps.build-ucvm.outputs.build-log }}
      shell: bash
### build cvmhlabn 
    - name: move to the model location
      run: (cd $UCVM_SRC_PATH/work/model)
      shell: bash
    - name: checkout cvmhlabn main
      uses: actions/checkout@v2
      with: 
        path: $RUNNER_WORKSPACE/cvmhlabn/ucvm/work/model/cvmhlabn
    - name: build cvmhlabn 
      run: ./.github/scripts/cvmhlabn-build.sh
      shell: bash

### check ucvm is still valid
    - name: check on ucvm
      run: (more $UCVM_INSTALL_PATH/install/conf/ucvm_env.sh)
      shell: bash

#    - run: ( echo " cvmhlabn-ucvm-ci2:pwd =>"; pwd;
#             echo " cvmhlabn-ucvm-ci2:ls =>"; ls;
#             echo " cvmhlabn-ucvm-ci2:RUNNER_WORKSPACE =>"$RUNNER_WORKSPACE;
#             echo " cvmhlabn-ucvm-ci2:github.action_path =>"${{ github.action_path }};)
#      shell: bash
#    - name: test cvmhlabn with ucvm
#      run: ./.github/scripts/cvmhlabn-test-ucvm.sh
#      shell: bash
